### ISSUE TITLE
Work items for CLI port/unblock OneASP.NET consumption

### ISSUE THREAD

**Issue by mlorbetske** [ligershark/mutant-chicken#67]
**Engine improvements**
- [ ] Support lookaround operators #63 (enables better comment support in XML-like documents)
- [ ] Support for importing remote resources #62 (enables selecting trains for .NET Core Projects)
- [ ] Parameter validation #65 (better experiences around selection, could enable bash completion)
- [ ] Allow blocks to be unprefixed when processing conditions #56 

**Migration blockers** (required to complete #57)
- [ ] Fix component load #61 
- [ ] Ensure dependencies are correct at install time #60 

**VS Integration Requirements**
- [ ] Figure out how to express pivots and classifications #58 and #47 
- [ ] Make sure that all required metadata is expressed #53 
- [ ] Solve the issue of conflicting component requirements #66

**Authoring Improvements**
- [ ] Allow templates to be packaged as part of tooling #54 (VS, XS?)
- [ ] Allow templates to advertise group membership #64
